<a href="https://colab.research.google.com/github/ryanaxiom/Applied-ML/blob/main/code/Carnegie_Day02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Student Instructions**: Before you begin, click **File > Save a copy in Drive** so you do not lose your work!

In [17]:
import pandas as pd
import numpy as np

url = ("https://raw.githubusercontent.com/ryanaxiom/Applied-ML/main/data/carnegie_data.csv")

carnegie = pd.read_csv(url, encoding="cp1252")

In [31]:
print(carnegie.shape)
display(carnegie)
print(carnegie.columns)
carnegie.dtypes

(3939, 101)

,unitid,name,city,stabbr,basic2000,basic2005,basic2010,basic2015,basic2018,basic2021,...,satv25,satm25,satcmb25,actcmp25,satacteq25,actfinal,appsf20,admitsf20,pctadmitf20,selindex
0,177834,A T Still University of Health Sciences,Kirksville,MO,52,25,25,25,25,25,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0
1,180203,Aaniiih Nakoda College,Harlem,MT,60,33,33,33,33,33,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,1.0
2,222178,Abilene Christian University,Abilene,TX,21,19,19,18,18,17,...,510.0,500.0,1010.0,21.0,19.0,19.921348,10534.0,6679.0,0.634042,2.0
3,138558,Abraham Baldwin Agricultural College,Tifton,GA,40,2,2,23,23,23,...,460.0,440.0,900.0,16.0,17.0,16.580470,2403.0,1826.0,0.759883,1.0
4,488031,Abraham Lincoln University,Glendale,CA,-2,-2,-2,-2,31,31,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3934,206695,Youngstown State University,Youngstown,OH,21,18,18,18,18,18,...,480.0,480.0,960.0,18.0,18.0,18.000000,8636.0,6039.0,0.699282,1.0
3935,375939,YTI Career Institute-Altoona,Altoona,PA,-2,-2,-2,7,7,10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3936,217077,YTI Career Institute-York,York,PA,40,10,10,7,7,7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3937,126119,Yuba College,Marysville,CA,40,3,3,1,7,8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3938,204255,Zane State College,Zanesville,OH,40,2,2,5,6,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Index(['unitid', 'name', 'city', 'stabbr', 'basic2000', 'basic2005',
       'basic2010', 'basic2015', 'basic2018', 'basic2021',
       ...
       'satv25', 'satm25', 'satcmb25', 'actcmp25', 'satacteq25', 'actfinal',
       'appsf20', 'admitsf20', 'pctadmitf20', 'selindex'],
      dtype='object', length=101)

unitid           int64
name            object
city            object
stabbr          object
basic2000        int64
                ...
actfinal       float64
appsf20        float64
admitsf20      float64
pctadmitf20    float64
selindex       float64
Length: 101, dtype: object

In [38]:
carnegie["totdeg"][[0,20,50,3000]]

0       1056
20        51
50       602
3000     572
Name: totdeg, dtype: int64

In [36]:
carnegie[["name","stabbr","totdeg"]]

                                         name stabbr  totdeg
0     A T Still University of Health Sciences     MO    1056
1                      Aaniiih Nakoda College     MT      32
2                Abilene Christian University     TX    1286
3        Abraham Baldwin Agricultural College     GA     715
4                  Abraham Lincoln University     CA      31
...                                       ...    ...     ...
3934              Youngstown State University     OH    2375
3935             YTI Career Institute-Altoona     PA      20
3936                YTI Career Institute-York     PA     167
3937                             Yuba College     CA     812
3938                       Zane State College     OH     285

[3939 rows x 3 columns]

In [40]:
carnegie[carnegie["control"] == 1]

,unitid,name,city,stabbr,basic2000,basic2005,basic2010,basic2015,basic2018,basic2021,...,satv25,satm25,satcmb25,actcmp25,satacteq25,actfinal,appsf20,admitsf20,pctadmitf20,selindex
1,180203,Aaniiih Nakoda College,Harlem,MT,60,33,33,33,33,33,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,1.0
3,138558,Abraham Baldwin Agricultural College,Tifton,GA,40,2,2,23,23,23,...,460.0,440.0,900.0,16.0,17.0,16.580470,2403.0,1826.0,0.759883,1.0
13,126182,Adams State University,Alamosa,CO,21,18,18,18,18,18,...,450.0,440.0,890.0,17.0,16.0,16.312155,1690.0,1688.0,0.998817,1.0
24,217615,Aiken Technical College,Graniteville,SC,40,2,2,4,4,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,126207,Aims Community College,Greeley,CO,40,3,3,8,3,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3929,420440,York County Community College,Wells,ME,40,1,1,2,5,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3930,218991,York Technical College,Rock Hill,SC,40,4,4,7,4,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3934,206695,Youngstown State University,Youngstown,OH,21,18,18,18,18,18,...,480.0,480.0,960.0,18.0,18.0,18.000000,8636.0,6039.0,0.699282,1.0
3937,126119,Yuba College,Marysville,CA,40,3,3,1,7,8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3938,204255,Zane State College,Zanesville,OH,40,2,2,5,6,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [44]:
carnegie[carnegie["totdeg"] > 5000]

,unitid,name,city,stabbr,basic2000,basic2005,basic2010,basic2015,basic2018,basic2021,...,satv25,satm25,satcmb25,actcmp25,satacteq25,actfinal,appsf20,admitsf20,pctadmitf20,selindex
27,999911,Air University,Montgomery,AL,-2,-2,-2,-2,32,18,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0
98,449339,American Public University System,Charles Town,WV,-2,-2,-2,18,18,18,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,1.0
134,197869,Appalachian State University,Boone,NC,21,18,18,18,18,18,...,540.0,530.0,1070.0,22.0,21.0,21.522146,18178.0,14453.0,0.795082,2.0
145,104151,Arizona State University Campus Immersion,Tempe,AZ,15,15,15,15,15,15,...,550.0,550.0,1100.0,21.0,22.0,21.474579,53516.0,47290.0,0.883661,2.0
146,483124,Arizona State University Digital Immersion,Scottsdale,AZ,-2,-2,-2,17,16,16,...,0.0,0.0,0.0,0.0,0.0,0.000000,5559.0,4035.0,0.725850,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3730,172644,Wayne State University,Detroit,MI,15,15,15,15,15,15,...,500.0,500.0,1000.0,20.0,19.0,19.171179,17093.0,11796.0,0.690107,2.0
3735,230782,Weber State University,Ogden,UT,22,19,19,18,18,18,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,1.0
3774,238032,West Virginia University,Morgantown,WV,15,16,16,15,15,15,...,520.0,510.0,1030.0,21.0,20.0,20.371650,17326.0,14535.0,0.838913,2.0
3783,433387,Western Governors University,Salt Lake City,UT,-2,22,22,18,18,18,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,1.0
3787,172699,Western Michigan University,Kalamazoo,MI,15,16,16,16,16,16,...,500.0,510.0,1010.0,20.0,19.0,19.252260,16582.0,14085.0,0.849415,2.0

In [53]:
carnegie.iloc[0:5]

,unitid,name,city,stabbr,basic2000,basic2005,basic2010,basic2015,basic2018,basic2021,...,satv25,satm25,satcmb25,actcmp25,satacteq25,actfinal,appsf20,admitsf20,pctadmitf20,selindex
0,177834,A T Still University of Health Sciences,Kirksville,MO,52,25,25,25,25,25,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0
1,180203,Aaniiih Nakoda College,Harlem,MT,60,33,33,33,33,33,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,1.0
2,222178,Abilene Christian University,Abilene,TX,21,19,19,18,18,17,...,510.0,500.0,1010.0,21.0,19.0,19.921348,10534.0,6679.0,0.634042,2.0
3,138558,Abraham Baldwin Agricultural College,Tifton,GA,40,2,2,23,23,23,...,460.0,440.0,900.0,16.0,17.0,16.580470,2403.0,1826.0,0.759883,1.0
4,488031,Abraham Lincoln University,Glendale,CA,-2,-2,-2,-2,31,31,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,1.0

In [58]:
carnegie["totdeg"].describe()

count     3939.000000
mean      1082.136075
std       2263.824902
min          0.000000
25%         95.000000
50%        365.000000
75%        991.000000
max      42484.000000
Name: totdeg, dtype: float64

In [59]:
carnegie["control"].value_counts()

control
2    1666
1    1628
3     645
Name: count, dtype: int64

In [64]:
print(carnegie["totdeg"].mean())
print(carnegie["totdeg"].median())
carnegie["totdeg"].std()

1082.136075145976
365.0

2263.824901943425

In [67]:
carnegie["name"].value_counts()

name
Columbia College                        4
Union College                           4
Southwestern College                    3
Lincoln University                      3
Bethel University                       3
                                       ..
Hagerstown Community College            1
Halifax Community College               1
Hallmark University                     1
Hamilton College                        1
Guilford Technical Community College    1
Name: count, Length: 3895, dtype: int64

In [68]:
carnegie["research"] = carnegie["serd"] + carnegie["nonserd"]
y = carnegie["research"].dropna()
y.shape

(302,)