<a href="https://colab.research.google.com/github/ryanaxiom/Applied-ML/blob/main/code/Day_04_Carnegie.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Student Instructions**: Before you begin, click **File > Save a copy in Drive** so you do not lose your work!

In [ ]:
import pandas as pd
import numpy as np

print(pd.__version__)
print(np.__version__)

url = ("https://raw.githubusercontent.com/ryanaxiom/Applied-ML/main/data/carnegie_data.csv")

carnegie_raw = pd.read_csv(url, encoding="cp1252")
carnegie = carnegie_raw.copy()

2.2.3
2.1.3

In [ ]:
carnegie["satcmb25"].describe()

count    2651.000000
mean      413.085628
std       511.886102
min         0.000000
25%         0.000000
50%         0.000000
75%       970.000000
max      1530.000000
Name: satcmb25, dtype: float64

In [ ]:
(carnegie["satcmb25"]==0).sum()

np.int64(1585)

In [ ]:
carnegie["research"] = carnegie["serd"] + carnegie['nonserd']
d = carnegie[carnegie["research"].notna()].copy()

In [ ]:
(d["satcmb25"]==0).sum()

np.int64(57)

In [ ]:
d["satcmb25"].describe()

count     302.000000
mean      919.337748
std       464.681749
min         0.000000
25%       952.500000
50%      1065.000000
75%      1180.000000
max      1530.000000
Name: satcmb25, dtype: float64

In [ ]:
print(d["satcmb25"].mean())
carnegie["satcmb25"].mean()

919.3377483443709

np.float64(413.0856280648812)

In [ ]:
carnegie["locale"].value_counts()

locale
 11    944
 21    797
 13    500
 12    459
 32    322
 41    260
 33    238
 22    112
 31     92
 42     88
 23     72
 43     51
-3       3
 25      1
Name: count, dtype: int64

In [ ]:
carnegie[carnegie["locale"]==-3]

,unitid,name,city,stabbr,basic2000,basic2005,basic2010,basic2015,basic2018,basic2021,...,satm25,satcmb25,actcmp25,satacteq25,actfinal,appsf20,admitsf20,pctadmitf20,selindex,research
724,243638,College of Micronesia-FSM,Pohnpei,FM,40,1,1,3,1,14,...,0.0,0.0,0.0,0.0,0.0,1352.0,1125.0,0.832101,1.0,NaN
740,376695,College of the Marshall Islands,Majuro,MH,40,1,1,1,1,14,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,1.0,NaN
2393,243647,Palau Community College,Koror,PW,40,1,1,7,1,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
d["medical"].mean()

np.float64(1.5264900662251655)

In [ ]:
carnegie["medical"].mean()

np.float64(1.9494795633409494)

In [ ]:
carnegie["med_yn"] = (carnegie["medical"] == 1).astype(int)
carnegie["med_yn"].mean()

np.float64(0.05052043665905052)

In [ ]:
d[["fallenr20","research"]].corr()

           fallenr20  research
fallenr20   1.000000  0.412425
research    0.412425  1.000000

In [ ]:
.412425**2

0.17009438062499999

In [ ]:
d[["serd","research"]].corr()

              serd  research
serd      1.000000  0.998813
research  0.998813  1.000000